# Generated by Django 3.1.3 on 2022-11-03 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0002_chart_singer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('song', models.CharField(max_length=200)),
                ('singer', models.CharField(max_length=200)),
                ('album', models.CharField(max_length=200)),
                ('like', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Top',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('song', models.CharField(max_length=200)),
                ('singer', models.CharField(max_length=200)),
                ('album', models.CharField(max_length=200)),
                ('like', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Chart',
            new_name='Nation',
        ),
    ]
