# Generated by Django 3.1.3 on 2022-11-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0003_auto_20221103_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nation',
            name='like',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='nation',
            name='rank',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sea',
            name='like',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sea',
            name='rank',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='top',
            name='like',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='top',
            name='rank',
            field=models.CharField(max_length=200),
        ),
    ]
