# Generated by Django 3.1.3 on 2022-11-03 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0004_auto_20221103_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nation',
            old_name='like',
            new_name='likem',
        ),
        migrations.RenameField(
            model_name='nation',
            old_name='rank',
            new_name='rankp',
        ),
        migrations.RenameField(
            model_name='sea',
            old_name='like',
            new_name='likem',
        ),
        migrations.RenameField(
            model_name='sea',
            old_name='rank',
            new_name='rankp',
        ),
        migrations.RenameField(
            model_name='top',
            old_name='like',
            new_name='likem',
        ),
        migrations.RenameField(
            model_name='top',
            old_name='rank',
            new_name='rankp',
        ),
    ]
