# Generated by Django 3.1.3 on 2022-11-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0005_auto_20221103_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nation',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sea',
            name='id',
        ),
        migrations.RemoveField(
            model_name='top',
            name='id',
        ),
        migrations.AlterField(
            model_name='nation',
            name='rankp',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sea',
            name='rankp',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='top',
            name='rankp',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
