# Generated by Django 3.1.3 on 2022-11-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0006_auto_20221103_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nation',
            name='likem',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='nation',
            name='rankp',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sea',
            name='likem',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sea',
            name='rankp',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='top',
            name='likem',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='top',
            name='rankp',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
